### ISSUE TITLE
Geo field is not created when using import form cli

### ISSUE THREAD

**Issue by nicksav** [algolia/algolia-csv-js#4]
nicksav$ algolia-upload appid key assets /Users/{user}/Documents/assets.csv --geo-colums="latitude","longitude"

It is adding columns, but not creating _geo field.

**Comment by Haroenv** [comment]
Could you show the csv you  used? it's required for `_geoLoc.lat`  &  `_geoLoc.lng` both are floats, not simply  integers.

**Comment by nicksav** [comment]
[assets.txt](https://github.com/algolia/algolia-csv-js/files/3367255/assets.txt)
Rename to csv

**Comment by Haroenv** [comment]
<img width="597" alt="Screenshot 2019-07-08 at 10 04 05" src="https://user-images.githubusercontent.com/6270048/60793310-b9a7dc00-a167-11e9-9d54-20c3dbd515b5.png">

Your csv works as expected for me fortunately/unfortunately.

**Comment by Haroenv** [comment]
Oh, I'm seeing the difference. Don't quote the fields you want to use for geo columns:

```
nicksav$ algolia-upload appid key assets /Users/{user}/Documents/assets.csv --geo-colums=latitude,longitude
```

**Comment by nicksav** [comment]
I have actually tried all options.
![image](https://user-images.githubusercontent.com/9266365/60794371-f9dd7d80-a1ac-11e9-951e-670652f06707.png)
![image](https://user-images.githubusercontent.com/9266365/60794401-0a8df380-a1ad-11e9-92d1-08e746eef53b.png)

**Comment by Haroenv** [comment]
Can you run `npx envinfo`? I run it exactly like that too. It works locally, as well as installed via npx:

```
npx algolia-csv XXXXX-app XXXX-key assets assets.csv --geo-columns=latitude,longitude
```

**Comment by nicksav** [comment]
System:
    OS: macOS 10.14.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 3.74 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 10.14. - /usr/bin/gcc
    Git: 2.22.0 - /usr/local/bin/git
  Servers:
    Apache: 2.4.34 - /usr/sbin/apachectl
  Virtualization:
    Parallels: 14.1.3 - /usr/local/bin/prlctl
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 26.0.2, 28.0.3, 29.0.0
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Emacs: 22.1.1 - /usr/bin/emacs
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.0 - /usr/bin/vim
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_144 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.1.23 - /usr/bin/php
    Python: 2.7.10 - /usr/bin/python
    Ruby: 2.3.7 - /usr/bin/ruby
  Databases:
    SQLite: 3.24.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1.1

**Comment by Haroenv** [comment]
Hmm, that's almost exactly the same as my setup

**Comment by nicksav** [comment]
will try on windows now, let's see

**Comment by Lolodrom** [comment]
Hello all :)

I had the same problem today and I think the documentation needs to be updated.
It is stated that the parameter should be --geo-colums but the actual code looks for --geo-columns with an "n" in columns.

Maybe this will solve your problem @Haroenv :D

**Comment by Haroenv** [comment]
Wow that's a very good catch, thanks @Lolodrom, it indeed needs to be `columns`, not `colums`
